workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic_api_key # Codemagic arayüzünde oluşturacağınız API Key ismi buraya gelecek
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tecnobis.fecrMeal # Bundle ID'nizi buraya yazdım, gerekirse güncelleyin
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be beautiful
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use signing files
        script: |
          keychain add-certificates
      - name: Install pods
        script: |
          find . -name "Podfile" -exec dir {} \;
          cd ios && pod install && cd ..
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true # TestFlight'a otomatik yükler
        beta_groups: # Opsiyonel: Test grubu adı
          - "Testers"
